## Importing Libraries

In [1]:
# import the required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

# do not display warnings in notebook 
import warnings
warnings.filterwarnings('ignore')

## Load Iris Dataset

In [2]:
from sklearn import datasets

dataset = datasets.load_iris()

### Insights on Dataset

In [3]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

Here we have a dataset whose description is given beforehand. Hence, we can directly apply simple machine learning models on it. However in cases where we do not have so much of information available, we need to explore and gain insights from the dataset better known as **[EDA](https://www.itl.nist.gov/div898/handbook/eda/section1/eda11.htm)**

The followind command prints the whole dataset. We can see that the dataset is in such a way that the instances are clustered together as classes i.e they are not distributed. Hence while training a model we have to pay attention to how we feed the instances.
We do not want to tain on first 100 instances and want to prdict outcomes on the next 50 because the model has not yet learnt on the third class yet

In [4]:
print(dataset)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

The dataset is didvided into the **dataset.data** and **dataset.target**.
Also, we do not want to print the whole dataset each time we need to look at the instances.
So, we print a few instances as follows using [slicing](https://python-reference.readthedocs.io/en/latest/docs/brackets/slicing.html).

In [5]:
print("Data \n",dataset.data[:5,:])
print("Target\n",dataset.target[:5])

Data 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Target
 [0 0 0 0 0]


Now we know how the dataset attributes look like. We continue EDA ahead (See remaining notebooks) where we see how data is distributed etc in form of Pair PLot and Pie charts and also how to use them. However sometimes we have attributes where the are nominal i.e. in words or are missing etc, in such cases we need to perform **Data Preprocessing**