# [Naive Bayes Classifier](https://en.wikipedia.org/wiki/Naive_Bayes_classifier)

## Importing Libraries

In [1]:
# import the required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

# do not display warnings in notebook 
import warnings
warnings.filterwarnings('ignore')

## Import dataset

In [2]:
from sklearn import datasets

dataset = datasets.load_iris()
data=pd.DataFrame(dataset.data)
target=pd.DataFrame(dataset.target)

Find out the number of classes and data columns

In [3]:
classes=target[0].unique()
print(classes)
print(len(data.columns))

[0 1 2]
4


Convert the data into numpy array. (can be done without it)

In [4]:
np_data=np.array(data)
print(np_data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

Rounding up the values of the data.

In [5]:
np_data_re=np_data[:,:].round()
print(np_data_re)
print(len(np_data_re))

[[5. 4. 1. 0.]
 [5. 3. 1. 0.]
 [5. 3. 1. 0.]
 [5. 3. 2. 0.]
 [5. 4. 1. 0.]
 [5. 4. 2. 0.]
 [5. 3. 1. 0.]
 [5. 3. 2. 0.]
 [4. 3. 1. 0.]
 [5. 3. 2. 0.]
 [5. 4. 2. 0.]
 [5. 3. 2. 0.]
 [5. 3. 1. 0.]
 [4. 3. 1. 0.]
 [6. 4. 1. 0.]
 [6. 4. 2. 0.]
 [5. 4. 1. 0.]
 [5. 4. 1. 0.]
 [6. 4. 2. 0.]
 [5. 4. 2. 0.]
 [5. 3. 2. 0.]
 [5. 4. 2. 0.]
 [5. 4. 1. 0.]
 [5. 3. 2. 0.]
 [5. 3. 2. 0.]
 [5. 3. 2. 0.]
 [5. 3. 2. 0.]
 [5. 4. 2. 0.]
 [5. 3. 1. 0.]
 [5. 3. 2. 0.]
 [5. 3. 2. 0.]
 [5. 3. 2. 0.]
 [5. 4. 2. 0.]
 [6. 4. 1. 0.]
 [5. 3. 2. 0.]
 [5. 3. 1. 0.]
 [6. 4. 1. 0.]
 [5. 4. 1. 0.]
 [4. 3. 1. 0.]
 [5. 3. 2. 0.]
 [5. 4. 1. 0.]
 [4. 2. 1. 0.]
 [4. 3. 1. 0.]
 [5. 4. 2. 1.]
 [5. 4. 2. 0.]
 [5. 3. 1. 0.]
 [5. 4. 2. 0.]
 [5. 3. 1. 0.]
 [5. 4. 2. 0.]
 [5. 3. 1. 0.]
 [7. 3. 5. 1.]
 [6. 3. 4. 2.]
 [7. 3. 5. 2.]
 [6. 2. 4. 1.]
 [6. 3. 5. 2.]
 [6. 3. 4. 1.]
 [6. 3. 5. 2.]
 [5. 2. 3. 1.]
 [7. 3. 5. 1.]
 [5. 3. 4. 1.]
 [5. 2. 4. 1.]
 [6. 3. 4. 2.]
 [6. 2. 4. 1.]
 [6. 3. 5. 1.]
 [6. 3. 4. 1.]
 [7. 3. 4. 1.]
 [6. 3. 4.

In [6]:
count_classes=np.zeros((len(classes),len(data.columns)))
#print(count_classes)

Count the number of instances present for each class.

In [7]:
count_in_each_class=target.count(axis=1).groupby(target[0]).count()
print(count_in_each_class)

0
0    50
1    50
2    50
dtype: int64


Input tuple.

In [8]:
# The input tuple
X=[7.0,3.0,6.0,2.0] 

In [9]:
def naive_bayes(np_data_re,target,classes,count_classes,count_in_each_class,X):
    for i in range(np_data_re.shape[1]):#col 0 1 2 3
        for j in range(np_data_re.shape[0]):#row 0  to 149(inclused)
            for k in range(classes.shape[0]):#classes 0 1 2
                if np_data_re[j,i]==X[i]:
                    if target[0][j]==classes[k]:
                        count_classes[k,i]+=1
    p=np.ones((len(classes),np_data_re.shape[1]))
    for i in range(len(count_classes)):
        for j in range(len(count_classes)):
            p[i][j]*=count_classes[i][j]/count_in_each_class[i]
    #print(p)
    m=[1]*p.shape[0]
    for j in range(p.shape[1]):
        for i in range(p.shape[0]):
            m[i]*=p[i][j]
    #         print(j,i)
            #print(m)
        m[i]/=count_in_each_class[i]
    return m

Our Prediction

In [10]:
m=naive_bayes(np_data_re,target,classes,count_classes,count_in_each_class,X)
print("Tuple X belongs to class:",m.index(max(m[0:])))

Tuple X belongs to class: 2


However naive bayes requires to discretize continuous values as we have done here which is not a very good approach. The above code can be applied to the data that has been carefully discretised.

Below is the naive bayes implementation using sklearn library.

In [11]:
#from sklearn import datasets
#iris = datasets.load_iris()
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
y_pred = gnb.fit(data, target).predict([X])
print("Tuple X belongs to class:",y_pred)

Tuple X belongs to class: [2]
